sudo: required

language: go

go:
  - 1.7.1

services:
  - docker

env:
  - GOOS=linux
  - GOARCH=amd64

install:
  - nvm install 6.1
  - cd client && npm install && cd -
  - go get ./...
  - go get github.com/opencontainers/runc/libcontainer/user

script:
  - ./build-docker.sh

after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker push jsalonen/swarmist
